services:
  - type: web
    name: ml-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 1 -b 0.0.0.0:5050 app:app"
    envVars:
      - key: PORT
        value: 5050
